<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Fb_FeederOperation" Id="{cda18660-b2b1-423c-9389-c10dbb890a58}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Fb_FeederOperation
VAR_INPUT
	nModeSelector	: FeederMode;
	bEnable         : BOOL;
END_VAR
VAR_OUTPUT
	bJogFwd         : BOOL;
	bJogRev         : BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="Fb_FeederOperation">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>